import pandas as pd
import streamlit as st
from PIL import Image

st.set_page_config(page_title="Naruverse", page_icon="🍥")

st.title("Akatsuki History")
st.image(Image.open("Naruto_app//images//aka.png"), use_column_width= True, clamp=True)

st.markdown("The initial concept of Akatsuki was devised by Black Zetsu as part of its plan to revive its mother, though it pretended the idea came from Madara Uchiha.")
st.markdown("Akatsuki was originally founded by Yahiko during the Third Shinobi World War alongside his childhood friends, Nagato and Konan. As citizens of Amegakure who had been orphaned by the Second Shinobi World War, the three created Akatsuki as a way to bring peace to their home country, which too often got caught in the crossfire of the Five Great Shinobi Countries' many conflicts. In time, the three were approached by Tobi, who introduced himself as Madara Uchiha. Tobi claimed Nagato was the reincarnation of the Sage of Six Paths and offered to teach him to control the power of his Rinnegan.")
st.image(Image.open("Naruto_app//images//3.png"), use_column_width= True, clamp=True)
st.markdown("With Yahiko's dying breath he entrusted the pursuit of peace to Nagato. Nagato, grieved by Yahiko's death, came to believe that the world would never willingly consent to peace and that Akatsuki's previously pacifist approaches to achieving that goal were therefore futile. He concluded that the only way the world would turn away from its constant warfare was to experience such catastrophic death and destruction that it could never again stomach the idea of conflict. Intending to be the one to show these horrors to the world, Nagato began using the alias Pain and formed the Six Paths of Pain, into which he integrated Yahiko's corpse so that he could symbolically continue leading Akatsuki. Nagato sought out Obito, under the guise of Madara Uchiha, and accepted his earlier offer of support, which he provided in secret.")
st.markdown("After the Third Shinobi World War, Akatsuki began recruiting S-rank missing-nin; mostly through strong-arming them and promising protection to carry out their respective goals. Orochimaru and Itachi joined for their own reasons, while Kisame and Zetsu joined to secretly ensure the Eye of the Moon Plan. Once Akatsuki recruited its target of ten members, Akatsuki began following a three-step process to achieve this stated objective:")
st.markdown("1. Obtain enough money to support their organisation.")
st.markdown("2. Provide mercenary services at well under the competitive rate, using the money gathered in the first step to offset costs. This will make countries increasingly dependent on Akatsuki's services, corner the entire market for shinobi missions, and eventually put all of the shinobi villages out of business because they can't compete with Akatsuki's prices. By capturing and strategically deploying the tailed beasts, Akatsuki could quickly start and then quell wars, thereby speeding up the process.")
st.markdown("3. Once all other major shinobi forces have dissolved, Akatsuki will be able to quickly conquer all the countries of the world.")

st.image(Image.open("Naruto_app//images//members.jpg"), use_column_width= True, clamp=True)
st.markdown("The early years of Nagato's Akatsuki were very successful, as the hidden villages increasingly hired Akatsuki to fight in wars and perform assassinations that the villages themselves were unwilling to get involved in during times of peace. ")
st.markdown("Nagato's actual objective behind acquiring the tailed beasts was to harness the tailed beasts' chakra to create a powerful kinjutsu, using it to wipe out one side in a conflict and, from the display, frighten the other side and the world at large to stop the fighting.")
st.image(Image.open("Naruto_app//images//gedo mini.jpg"), use_column_width= True, clamp=True)
st.markdown("After years of inactivity, the Akatsuki's return with the mission to capture the tailed beasts gradually elevates them from the shadows of the world and, in turn, prompts a growing resistance by the hidden villages. After Deidara captures the One-Tail, Sasori is killed in battle with the Suna and Konoha forces sent to rescue the One-Tail's jinchūriki. Obito takes this open position as an opportunity to officially join Akatsuki as Tobi, helping capture the Three-Tails. Around the same time, Hidan and Kakuzu capture the Two-Tails, but both are subsequently defeated in unrelated confrontations with Konoha's Nijū Shōtai. Kisame Hoshigaki later acquires the Four-Tails, after which both Deidara and Itachi separately die in battle against Sasuke Uchiha.")
st.markdown("Because of their shrinking numbers, Tobi pressures Nagato into taking a more active role in capturing the remaining tailed beasts. In the anime, he and Konan are first sent to capture the Six-Tails, which was captured at some earlier point in the manga. They are afterwards sent to Konoha to capture the Nine-Tails, and in the course of the resultant Pain's Assault the village is destroyed. When he finally locates and meets with the Nine-Tails' jinchūriki, Naruto Uzumaki, Nagato begins to doubt the direction he has taken Akatsuki in since Yahiko's death. After Nagato's Six Paths of Pain are defeated in battle and Konoha and its population saved, Naruto after hearing Nagato's story is swayed not to kill Nagato and instead convinces him that a bloodless peace is worth pursuing no matter how impossible it may seem. To make up for all the missteps he took, Nagato gives his life to revive the Konoha villagers that died during his attack, using his last breath to encourage Naruto to achieve the peace that he was never able to. With Yahiko and Nagato gone, Konan opts to leave Akatsuki.")
st.markdown("Tobi approached Akatsuki in order to get close to Nagato, whose Rinnegan he needed to complete the Eye of the Moon Plan. Over the years, he remained in the shadows, allowing Nagato to stay as Akatsuki's leader while Obito manipulated him towards his desired ends, specifically capturing all nine tailed beasts so that he can restore the Ten-Tails and use it to cast the Infinite Tsukuyomi on the world, ending all conflict by trapping everyone in a dream. Obito follows the Eye of the Moon Plan under instructions of the real Madara Uchiha, whose identity Obito assumed after Madara's death. Madara intended Obito to have Nagato revive him in the final stages of the plan, though Obito had no plans to uphold that end of the plan and intended to use Nagato to revive himself should anything happen to him. However, this subterfuge was rendered moot by Nagato betraying Obito and using the Samsara of Heavenly Life Technique to revive everyone he killed during his invasion of Konoha.")
st.image(Image.open("Naruto_app//images//jubi.png"), use_column_width= True, clamp=True)
st.markdown("Obito's increasing involvement in Akatsuki's activities following Itachi Uchiha's death. Obito forms alliances and pursues the capture of the Eight-Tails and Nine-Tails, but faces setbacks and betrayals, leading to the initiation of the Fourth Shinobi World War. Obito reluctantly collaborates with Kabuto to strengthen Akatsuki, but faces challenges in the war. Obito becomes the Ten-Tails' jinchūriki but is defeated by Naruto and Sasuke, halting the Eye of the Moon Plan. After surrendering, Obito attempts redemption but is manipulated by Black Zetsu, leading to the revival of Madara Uchiha. Madara engages in battles, ultimately activating the Infinite Tsukuyomi, but is betrayed by Black Zetsu, revealing a plan to revive Kaguya Ōtsutsuki. Team 7, with Obito's assistance, defeats Kaguya and Black Zetsu, ending the Infinite Tsukuyomi. Madara succumbs to the extraction of Tailed Beasts, and Naruto and Sasuke's final fight concludes with the destruction of the Valley of the End.")
st.image(Image.open("Naruto_app//images//battle.jpg"), use_column_width= True, clamp=True)
